//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLTestAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_method_response_parameters
    {
        public int application_method_response_id { get; set; }
        public int application_method_id { get; set; }
        public string application_method_response_parameter_name { get; set; }
        public Nullable<int> is_container { get; set; }
        public Nullable<int> position { get; set; }
        public string value { get; set; }
    }
}
