//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLTestAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_method
    {
        public int application_method_id { get; set; }
        public int application_id { get; set; }
        public int application_version_id { get; set; }
        public string method_name { get; set; }
        public string return_type { get; set; }
    }
}
