USE [master]
GO

/****** Object:  Database [TestAutomation]    Script Date: 2/4/2019 10:29:36 AM ******/
CREATE DATABASE [TestAutomation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestAutomation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TestAutomation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestAutomation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TestAutomation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TestAutomation] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestAutomation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestAutomation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestAutomation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestAutomation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestAutomation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestAutomation] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestAutomation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestAutomation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestAutomation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestAutomation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestAutomation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestAutomation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestAutomation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestAutomation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestAutomation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestAutomation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestAutomation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestAutomation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestAutomation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestAutomation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestAutomation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestAutomation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestAutomation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestAutomation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestAutomation] SET  MULTI_USER 
GO

ALTER DATABASE [TestAutomation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestAutomation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestAutomation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestAutomation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestAutomation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestAutomation] SET QUERY_STORE = OFF
GO

USE [TestAutomation]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TestAutomation] SET  READ_WRITE 
GO

