ALTER SERVER ROLE [sysadmin] ADD MEMBER [LAPTOP-DHCHDQG6\Jeremy];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

